### PR TITLE
#972 - Fixed the UnitOfWork.begin() JavaDoc to reflect the implementation

### PR DESCRIPTION
**Pull request by jccarrillo**
Following the #972 issue, this revision fixes the javadoc.

### CODE REVIEW

**Comment by jccarrillo** [comment]
I signed it.

jc


Date: Thu, 7 Jan 2016 13:09:50 -0800

**Comment by jccarrillo** [comment]
I signed it!

jc


Date: Thu, 7 Jan 2016 13:09:50 -0800

**Comment by jccarrillo** [comment]
Is there anything else needed for approval?

**Comment by sameb** [comment]
The implementation was changed to respect the javadoc in https://github.com/google/guice/commit/3e21a13dfed292dbfa798f7d64f93f641c8d8cd5.

**Pull request closed without merging**
