### PR TITLE
upgrade to java 10

### PR DESCRIPTION
**Pull request by flashboss**
here an upgrade to java 10. The upgrade is tested through the junit tests. Missing the following subprojects to test: 
[INFO] Google Guice - Extensions - Persist ................ FAILURE [  5.614 s]
[INFO] Google Guice - Extensions - Servlet ................ SKIPPED
[INFO] Google Guice - Extensions - Spring ................. SKIPPED
[INFO] Google Guice - Extensions - Struts2 ................ SKIPPED
[INFO] Google Guice - Extensions - ThrowingProviders ...... SKIPPED
[INFO] Google Guice - Extensions - TestLib ................ SKIPPED
[INFO] Google Guice - JDK10 Tests 4.2.1-SNAPSHOT .......... SKIPPED

### CODE REVIEW

**Comment by flashboss** [comment]
Ok .  The other subprojects work. Missing only to test the following projects:

[INFO] Google Guice - Extensions - Persist ................ FAILURE [ 5.614 s]
[INFO] Google Guice - Extensions - Servlet ................ SKIPPED
[INFO] Google Guice - Extensions - Struts2 ................ SKIPPED

**Comment by flashboss** [comment]
I'm signed it

**Comment by dimo414** [comment]
What's the motivation for this PR? Is Guice not working in your project? Guice is intentionally still on Java 8 in order to support such users.

**Comment by flashboss** [comment]
hi. I see many other opensource projects use Guice. They are moving on java 10, so they are forced to delete Guice as dependency unless Guice move to java 10 too

**Comment by dimo414** [comment]
> they are forced to delete Guice as dependency unless Guice move to java 10 too

Can you share some concrete examples of this? We are not aware of any such limitation, and it's unlikely that upgrading Guice to Java 10 (which *would* break all projects that haven't updated) is the appropriate fix. There should be no problem with a Java 10 project depending on Guice.

**Comment by michelemauro** [comment]
An example is Lightbend's Lagom Framework: it is based on Play! Framework, which uses Guice. It is stuck on Java 8 until these problems are sorted out. They have recently decided to jump directly to 11 (citing Cassandra's team same decision).

Work on Guice for JDK 10/11 seems ongoing here:
https://github.com/google/guice/pull/1169

Relevant discussions:
https://github.com/playframework/playframework/issues/8454
https://github.com/lagom/lagom/issues/1276
https://github.com/lagom/lagom/issues/1417

Thanks to all the contributors for their work!

**Comment by dimo414** [comment]
Thanks for the cross-reference @michelemauro - #1169 is definitely a more appropriate fix than updating Guice wholesale.

**Pull request closed without merging**
