### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by ghatwala**
adding power support.

### CODE REVIEW

**Comment by sameb** [comment]
Can you elaborate on why you want to do this and what purpose it serves?

This will not change anything about Guice, it will just change the way it's continuous integration tests run.

**Comment by ghatwala** [comment]
@sameb - we would want to have CI run to happen on different arch (ppc64le) too to have regression happening on power too fo this repo.

**Comment by sameb** [comment]
Why?  Guice has no interaction with low level native architectures.  Do you have some reason to suspect otherwise?

**Comment by ghatwala** [comment]
I signed it!

**Pull request closed without merging**
