### PR TITLE
Ci test java versions

### PR DESCRIPTION
**Pull request by carldea**
Test main versions of Java on Ubuntu.

Signed-off-by: Carl Dea <carl.dea@gmail.com>

### CODE REVIEW

**Comment by carldea** [comment]
This is using GitHub actions to build and test the library on major Java versions.

**Comment by carldea** [comment]
I signed the CLA, not sure how to refresh to have it green check mark :-)

**Comment by ogregoire** [comment]
> 
> 
> I signed the CLA, not sure how to refresh to have it green checked mark :-)

>> Once you've signed (or fixed any issues), please reply here with @googlebot I signed it! and we'll verify it.

**Comment by carldea** [comment]
@googlebot I signed it!

**Comment by carldea** [comment]
> > I signed the CLA, not sure how to refresh to have it green checked mark :-)
> 
> > > Once you've signed (or fixed any issues), please reply here with @googlebot I signed it! and we'll verify it.

@googlebot I signed it!

**Comment by markmarch** [comment]
Thanks for working on this, however we use Travis CI and the code is tested again Java 8, 11, and 15. See https://github.com/google/guice/blob/master/.travis.yml and https://travis-ci.org/github/google/guice/builds/747738966

**Comment by carldea** [comment]
Things to consider why this project should move to GitHub CI and use Github Actions:

Some advantages:
- Well Integrated (the user interface is another tab in your project on GitHub as opposed to another site)
- Github runners (up to four concurrent are free). Travis is phasing out the free service of runners for newer projects.
- The new underlying GitHub Actions for setting up Java uses an LTS version of OpenJDK without worries about Oracle's new commercial license requirements. You just want to built and test or deploy your artifacts. Also, OpenJDK versions from 6 to 17ea is supported.
- GitHub CI is much simpler by using its matrix of OSes and Java versions. If you should choose to add or update to newer OSes or Java versions respectively. 

There are literally hundreds of article on good reasons why, but I found this article that describes the state of Travis CI:
https://www.jeffgeerling.com/blog/2020/travis-cis-new-pricing-plan-threw-wrench-my-open-source-works

**Pull request closed without merging**
