### PR TITLE
JPMS Guice Strict Naming

### PR DESCRIPTION
**Pull request by GedMarc**
This pull request creates the module-info.class files in the package for <JDK9 compiles.

This uses Moditect to create the module-info files, and strictly names the packages for JPMS correctly, enabling transitive requires, and not placing Guice in the Automatic Module pool.

### CODE REVIEW

**Comment by ronshapiro** [comment]
FYI that we've traditionally stayed away from having module-info classes and more towards using Automatic-Module-Name in the manifest.

**Comment by GedMarc** [comment]
Yes, But it's not going to work for much longer now that JPMS is in full swing,

**Automatic Module Names are not JPMS**, they are a place holder for what the module will be named when ported at a later date, that date being today for Guice.
Using automatic module names was a great interim, but it still places the module in the "UNNAMED-MODULES", negating all modular features.

The automatic module is still found as file-referenced, and does not support "requires transitive"
The automatic module does not define exposures or requirements and is operated on in classpath mode.
The automatic module uses no modular pathing of any kind

This solution is what was used for ClassGraph (Duke Award Winner), and is definitely the recommended way of strictly naming JPMS modules for compatibility with older builds.

I see you are still building in Travis with JDK 7 itself, instead of just building in JDK 8 with source and target of 1.7, so I've pulled the moditect out for that build, if you are packaging and deploying to central on this, then this pull request will have no impact.

Take it or leave it lol ;) 

It's currently building across all builds (1.7 is compiling in JDK 1.8 with source and target set, the enforcer is making sure it's 1.7 compatible) at https://jwebmp.com/teamcity/viewLog.html?buildId=201509&tab=buildResultsDiv&buildTypeId=GuiceJpms_BuildGuice423jpms

I'm using it as a pure JPMS with jndi, persist and servlet.

**Comment by GedMarc** [comment]
Tadaaaa, there we have it.

I'm going to branch off in my fork, and force JRE11 builds with module-info now, 

You can kill off, review, or merge this request at your leisure.

**Comment by GedMarc** [comment]
You can view the output at the following location (This is deploying to the JWebMP Artifactory)
https://jwebmp.com/teamcity/viewLog.html?buildId=201539&tab=buildResultsDiv&buildTypeId=GuiceJpms_BuildGuice423jpms

All artifacts available at https://jwebmp.com/teamcity/viewLog.html?buildId=201539&buildTypeId=GuiceJpms_BuildGuice423jpms&tab=artifacts

Login as Guest to view.

**Comment by kashike** [comment]
It is worth noting that `javax.inject` and `aopalliance` are still unnamed, as well.
___
`com.google.inject.util` should also be exported.

**Comment by GedMarc** [comment]
I did notice this, I did not export com.google.inject to any random, but only to specified modules that use it within the source structure. 
As a util's package these should not be publicly visible and only used for internal API's (The point of JPMS in effect)

aopalliance I don't think will ever be named, I scouted hard for an up to date and closest I got was com.github.aopalliance but the physical classes are in a different package. 
It is going to be very annoying to have to specify the requires in every base module however simply because Guice uses it (It assumes automatic-named/file-named packaging and gets placed with java.base) as Guice was before this pull request.

I'm still debating whether or not to create the source package and simply package, but the original sourceforge has been removed and the cvs that it was located on has been turned off. Only they (the creators) will be able to deploy to maven an official update to the aopalliance-core project.

**Comment by kashike** [comment]
`com.google.inject.util` is part of the API, while `com.google.inject.internal.util` is not.

**Comment by GedMarc** [comment]
Ping :)

Anything you guys need me to do to get this pulled in?

**Comment by GedMarc** [comment]
Ping....

**Comment by GedMarc** [comment]
fork it - not worth working with you guys

**Pull request closed without merging**
