### PR TITLE
Moved JUnit dependency to Dependency Management

### PR DESCRIPTION
**Pull request by jccarrillo**
JUnit 4.12 Release Notes:
https://github.com/junit-team/junit/blob/master/doc/ReleaseNotes4.12.md

Both maven and ant were updated.

### CODE REVIEW

**Comment by jccarrillo** [comment]
@sameb please look into this PR as it is needed for the JUnit work that I'm doing in https://github.com/google/guice/pull/979

**Comment by sameb** [comment]
Does this use 4.12 features that weren't in 4.11?  We're on 4.11 internally and I'd like to avoid skew if possible.

**Comment by jccarrillo** [comment]
Looking into this

**Comment by jccarrillo** [comment]
It wasn't needed. I reverted and committed a change to move the JUnit dependency into the DM.

**Comment by jccarrillo** [comment]
Just modified the title of this PR.

**Comment by sameb** [comment]
Thanks!  Once Travis is clean I'll merge.

**Comment by sameb** [comment]
Actually, @jccarrillo, would you mind squashing the older commits to cleanup the commit history on the merge?

**Pull request closed without merging**
