### PR TITLE
Bump asm version to 6.2 for JDK 10/11 support

### PR DESCRIPTION
**Pull request by svrakitin**

### CODE REVIEW

**Comment by svrakitin** [comment]
Signed CLA.

**Comment by svrakitin** [comment]
We signed it.

**Comment by ronshapiro** [comment]
Try "I signed it!" - the bot may not be smart enough to detect "we"

**Comment by svrakitin** [comment]
I signed it!

**Comment by svrakitin** [comment]
I signed it.

**Comment by svrakitin** [comment]
I signed it!

**Comment by svrakitin** [comment]
Is there anything I can do to speed up the process of getting this to master? ;)

**Comment by mkurz** [comment]
Getting this merged would be really really great! :+1:

**Comment by sameb** [comment]
this looks reasonable, but can someone please clarify what about JDK10 fails w/ guice?  also, can someone update the travis config to run over jdk10 too?

@netdpb i think the preferred way to do PRs now is to submit them internally w/ MOE (which i think has a way to pull in PRs and retain the author metadata?) and then push it back out.  @ronshapiro might know.

**Comment by svrakitin** [comment]
@sameb asm's ClassReader will simply fail to read .class files with bytecode of 54.0 version.

Travis doesn't have jdk10 target yet. ;(

**Comment by svrakitin** [comment]
Any update on this?

**Comment by mkurz** [comment]
FYI: ASM 6.2 released with better JDK 10 support and even with JDK 11 support already!
http://asm.ow2.io/versions.html
https://gitlab.ow2.org/asm/asm/tags
https://gitlab.ow2.org/asm/asm/issues/317830

**Comment by eximius313** [comment]
+1 for ASM 6.2

**Comment by pettyjamesm** [comment]
Any update on the timeline for this to make it into a release? Would be great to be able to use guice on newer JVMs.

**Comment by ronshapiro** [comment]
We have run into a bumps in the road in upgrading this, but we are working on resolving them

**Comment by ronshapiro** [comment]
Would it make sense to recommend that users bring their own copy of ASM if they care about the Java version they want to support? Is this simply just adding a different version of the library on the classpath?

**Comment by mkurz** [comment]
Is there a actually a reason why Guice bundles the asm in the final package? Why not keep it as normal dependency so users can just override it?

**Comment by sameb** [comment]
I believe the historical reason was the ASM did not guarantee compatibility
between releases, so shading it was effectively required.  I think as the
past few ASM releases, that's not true anymore... so perhaps we can stop
shading asm?

**Comment by mcculls** [comment]
Note that the build already produces a version of Guice that doesn't bundle asm or cglib:

http://repo1.maven.org/maven2/com/google/inject/guice/4.2.0/guice-4.2.0-classes.jar

This is a jar of the Guice classes before any JarJar'ing.

Also if you don't need AOP then there's the "no_aop" jar which doesn't use asm/cglib at all:

http://repo1.maven.org/maven2/com/google/inject/guice/4.2.0/guice-4.2.0-no_aop.jar

**Comment by prodsey** [comment]
This is great. 
We are planning to migrate an enterprise project  (extensively uses guice ) from JDK 9 to JDK 10
Any ballpark ETA on this change to support  JDK  10?
Thanks

**Comment by prodsey** [comment]
Any update on when can we expect jdk 10, 11 supported release?

**Comment by prodsey** [comment]
Below exception on startup with 4.2 release + JDK 10
I am thinking this is related?

Any update on the release?

Caused by: java.lang.IllegalArgumentException
	at com.google.inject.internal.asm.$ClassReader.<init>(ClassReader.java:160)
	at com.google.inject.internal.asm.$ClassReader.<init>(ClassReader.java:143)
	at com.google.inject.internal.asm.$ClassReader.<init>(ClassReader.java:418)
	at com.google.inject.internal.cglib.proxy.$BridgeMethodResolver.resolveAll(BridgeMethodResolver.java:69)
	at com.google.inject.internal.cglib.proxy.$Enhancer.emitMethods(Enhancer.java:1132)
	at com.google.inject.internal.cglib.proxy.$Enhancer.generateClass(Enhancer.java:630)
	at com.google.inject.internal.cglib.core.$DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
	at com.google.inject.internal.cglib.core.$AbstractClassGenerator.generate(AbstractClassGenerator.java:329)

**Comment by svrakitin** [comment]
@prodsey this is original issue :)

**Comment by prodsey** [comment]
thanks @svrakitin 

any ETA on when this will be released?

I tried with with  
<classifier>no_aop</classifier> and additionally including ASM 6.2 and cglib 3.2.6 (did not work)

any other way I can start testing with JDK 10?

**Comment by himanshukandwal** [comment]
Facing the same issue after applying the suggested fixes. 

Caused by: java.lang.IllegalArgumentException
        at com.google.guice@4.2.0/com.google.inject.internal.asm.$ClassReader.<init>(ClassReader.java:160)
        at com.google.guice@4.2.0/com.google.inject.internal.asm.$ClassReader.<init>(ClassReader.java:143)
        at com.google.guice@4.2.0/com.google.inject.internal.asm.$ClassReader.<init>(ClassReader.java:418)
        at com.google.guice@4.2.0/com.google.inject.internal.util.LineNumbers.<init>(LineNumbers.java:64)
        at com.google.guice@4.2.0/com.google.inject.internal.util.StackTraceElements$1.load(StackTraceElements.java:49)
        at com.google.guice@4.2.0/com.google.inject.internal.util.StackTraceElements$1.load(StackTraceElements.java:45)
        at com.google.common@23.6-android/com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3443)
        at com.google.common@23.6-android/com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2169)
        at com.google.common@23.6-android/com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2128)
        at com.google.common@23.6-android/com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2041)

**Comment by mcculls** [comment]
@prodsey what was the error you had with the 'no_aop' jar? That doesn't use ASM or CGLIB at all, but at the same time you won't have access to any AOP features such as method interception. If you're still seeing ASM related errors with the 'no_aop' jar then check your classpath in case it contains another version of Guice.

If you want to try Guice with AOP and a different version of ASM/CGLIB then you should take the [classifier]classes[/classifier] jar and add ASM 6.2 and CGLIB 3.2.6 as separate dependencies. Again making sure the original Guice jar isn't being dragged onto the same project classpath.

( of course an official release with this version bump would also be appreciated! )

**Comment by prodsey** [comment]
@mcculls
With no_aop and asm 6.2 + latest cglib I got the same exception .... checked dep hierarchy and removed all older versions of guice. But still got the same exception. I need method interceptors. I have not tried [classifier]classes[/classifier] . Should that work?

I agree, an official release with JDK 10,11 support will definitely help.

@sameb 
Can you please throw some light on when can we expect an official release?

**Comment by prodsey** [comment]
@mcculls
Thanks for the input. [classifier]classes[/classifier] works fine when you include asm 6.2 and cglib JARs. I did some basic testing with OpenJDK 10.0.1.

I guess this is a good option till the official release right? Do you see any downside?

**Pull request closed without merging**
