### PR TITLE
Moe Sync

### PR DESCRIPTION
**Pull request by ronshapiro**
This code has been reviewed and submitted internally. Feel free to discuss on the PR and we can submit follow-up changes as necessary.

Commits:
=====
<p> Update guice opensource asm dep to 6.2.

af1dc88a809bf21f6f7971c0216ec0ede7de0f7f

Fixes https://github.com/google/guice/pull/1169

### CODE REVIEW

**Comment by mkurz** [comment]
@ronshapiro Thanks to asm 6.2 you can now also add
```
jdk:
  - oraclejdk11
  - oraclejdk10
```
to `.travis.yml`

**Comment by ronshapiro** [comment]
@mkurz it's on its way! Already submitted internally, it will be in the next sync

**Comment by mkurz** [comment]
@ronshapiro Great!
What about that comment [here](https://github.com/google/guice/pull/1169#issuecomment-395095124)? Is shading asm actually necessary anymore nowadays?

**Comment by ronshapiro** [comment]
Thanks for bringing that back up - I opened up
https://github.com/google/guice/issues/1198 to track that specifically.

**Comment by mkurz** [comment]
@ronshapiro Great, thanks!

**Comment by mkurz** [comment]
FYI: asm 6.2.1 is available

**Pull request merged**
