### PR TITLE
Moe Sync

### PR DESCRIPTION
**Pull request by ronshapiro**
This code has been reviewed and submitted internally. Feel free to discuss on the PR and we can submit follow-up changes as necessary.

Commits:
=====
<p> Run tests on JDK 10 and 11 now that ASM has been updated to 6.2

c4922f03c3f4dbd4d43555a8bd86ec2c71c5635f

### CODE REVIEW

**Comment by ronshapiro** [comment]
@sameb any idea what the two JDK 11 failures are?

**Comment by sameb** [comment]
The maven build hides its error output for some reason, but the ant build doesn't.  Here's the error:

```
[junit] 1) testInterceptingNonBridgeWorks(com.google.inject.MethodInterceptionTest)junit.framework.AssertionFailedError: expected:<1> but was:<0>
    [junit] 	at com.google.inject.MethodInterceptionTest.testInterceptingNonBridgeWorks(MethodInterceptionTest.java:323)
    [junit] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    [junit] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    [junit] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```

Looks like something changed about the way bridge methods work (or are detected?) in JDK11?

**Comment by ronshapiro** [comment]
@sameb looks like we now have a few straggling test failures :-/

**Comment by sameb** [comment]
Blargh, testlib broken. I'll figure it out. Thanks for trying again.

**Pull request merged**
