### PR TITLE
Added option to configure PersistFilter to assume persistence service is initialized

### PR DESCRIPTION
**Pull request by lextiz**
Please see: https://github.com/google/guice/pull/922

### CODE REVIEW

**Comment by lextiz** [comment]
Could anyone please review this  pull request?

**Comment by lextiz** [comment]
Please review the PR.

**Comment by sameb** [comment]
Sorry for the delay.

Is there a way to make this work by adding a binding to a module or configuring the way the persist modules are installed, as opposed to reading a string in a properties file?

**Comment by lextiz** [comment]
If by "make this work" you mean passing configuration to PersistFilter, then I do not see such way. Passing configuration to a servlet filter is limited by filter api, and the PersistFilter itself is not managed by guice (it is managed by servlet container).

**Comment by lextiz** [comment]
@sameb kind review reminder

**Comment by lextiz** [comment]
Please review this PR.

**Comment by GaspardPO** [comment]
This PR last interaction was more than 1 year ago.
Will it still be merged, or could it be closed?

**Comment by lextiz** [comment]
The content is still relevant, the only matter is the code review and merge.

**Comment by sameb** [comment]
https://github.com/google/guice/commit/3e21a13dfed292dbfa798f7d64f93f641c8d8cd5 updated the code to ignore subsequent start() calls, so this should no longer be necessary.

**Pull request closed without merging**
