### PR TITLE
Remove link that's gone 404

### PR DESCRIPTION
**Pull request by elharo**
@sameb

### CODE REVIEW

**Comment by elharo** [comment]
Thanks @maheshwarigagan. I don't have merge privileges here so someone else needs to merge.

**Comment by elharo** [comment]
Ping @maheshwarigagan @sameb Can someone merge this? Thanks.

**Comment by elharo** [comment]
Ping. Can someone merge this?

**Comment by dimo414** [comment]
Thanks for the ping, this has been fixed.

**Pull request closed without merging**
