### PR TITLE
Exclude transitive ant dependency from cglib because we don't need it

### PR DESCRIPTION
**Pull request by mcculls**
There are a couple of issues against cglib to fix this upstream (such as https://github.com/cglib/cglib/pull/87) until then this is a quick local fix.

### CODE REVIEW

**Comment by AlexeyRedinskii** [comment]
Hello guys,
any chances to merge that in? Ant make the 3.2.10 library not JDK11 compatible.

**Comment by AlexeyRedinskii** [comment]
Hello guys,
any chances to merge that in? Ant make the CGlib 3.2.10 library not JDK11 compatible.

**Comment by GedMarc** [comment]
I'm using it fine what do you mean?

If you need a JPMS guice compatible (as not JDK11/Classpath) you can use the strictly named
https://search.maven.org/search?q=g:com.jwebmp.inject
and for the xtensions
https://search.maven.org/search?q=g:com.jwebmp.inject.extensions

Don't forget to add -add-opens=java.lang/java.base=com.google.inject

**Comment by AlexeyRedinskii** [comment]
@GedMarc you see, since Ant dependency is pulled as required, not optional, it makes CGLib not JDK11 compatible. 
+--- cglib:cglib:3.2.10
+---- org.apache.ant:ant:1.10.3
The latest Ant library version at the moment is 1.10.5, which still has some code referencing CORBA related classes and referencing removed methods from JDK via reflection. This library will very likely crash at runtime under certain circumstances. I don't know what plans Ant community has on releasing a JDK11 compatible version, but if you could remove Ant from CGLib dependencies, it would be awesome.

**Comment by sameb** [comment]
i'll merge in upstream and release a new cglib rather than doing this exclusion.

out of pure curiosity, does the output of some tool really contain that ant emoji, or did you write that manually? :-)

**Comment by AlexeyRedinskii** [comment]
You can do that by starting a word with ":" The editor will popup emojies to choose from :)

**Comment by dimo414** [comment]
It should have said `org.apache.ant:ant:1.10.3` but GitHub mangled it.

**Comment by mcculls** [comment]
No longer needed as cglib dependency has been removed

**Pull request closed without merging**
