### PR TITLE
New Version with Jakarta support

### PR DESCRIPTION
**Pull request by fcorreia**
Proposal for a new major version, since support for Jakarta DI is a breaking change.

List of changes:
 * Jakarta Support
 * JDK 17 LTS, because is the latest LTS version
 * upgrade some versions

NOTE: Plugin `animal-sniffer-maven-plugin` not enabled, is this required for jdk >=9

### CODE REVIEW

**Comment by GedMarc** [comment]
https://mvnrepository.com/artifact/com.guicedee.services/guice

**Comment by GedMarc** [comment]
https://mvnrepository.com/artifact/com.guicedee.services/guice/1.2.2.1-jre17

**Comment by GedMarc** [comment]
https://mvnrepository.com/artifact/com.guicedee.services/guice-servlet/1.2.2.1-jre17

**Comment by sameb** [comment]
This will not be integrated.  It erases javax.inject.* support, which is not something we're going to do.

**Pull request closed without merging**
