### PR TITLE
Jdk11 compatibility

### PR DESCRIPTION
**Pull request by davido**
Switch to experimental asm API that supports JDK11.

### CODE REVIEW

**Comment by cushon** [comment]
What are the compatibility implications of this? The docs [1] for `ASM7_EXPERIMENTAL` say:

> Experimental, use at your own risk. This field will be renamed when it becomes stable, this will break existing code using it.

So there's going to be a source compatibility issue, but I'm not sure if it's also a binary compatibility issue: `ASM7_EXPERIMENTAL` is a `static final` field that will be inlined, but will future ASM releases continue to accept that option, or will the eventual non-experimental `ASM7` have a different value?

[1] https://gitlab.ow2.org/asm/asm/blob/3f7d6ba206ec6280a584bc135cd86c2b2cf5c279/asm/src/main/java/org/objectweb/asm/Opcodes.java#L50

**Comment by mkurz** [comment]
@davido I think just updating the `pom.xml` isn't enough: You also have to upgrade the `jar` file, see how that was done earlier: #1197 (and also #1169)

**Comment by davido** [comment]
@mkurz, Ah thanks for pointing this out. Apparently Guice is supporting both build tools Apache Ant and Apache Maven? I tested this PR with Maven and it worked for Gerrit Code Review purpose (Build and run with JDK11).

**Comment by frankgrimes97** [comment]
OpenJDK 11 has now been released... any ETA on when we might expect this to be addressed?

**Comment by mkurz** [comment]
@frankgrimes97 See these comments here: https://github.com/google/guice/issues/1198#issuecomment-423221773 - Seems like we get an updated Guice very soon.

**Pull request closed without merging**
