### PR TITLE
Bump ASM version to 9.0 to support JDK 15/16

### PR DESCRIPTION
**Pull request by mkurz**
ASM 9.0, which brings support for Java 15 and even Java 16 already just got released:
* https://gitlab.ow2.org/asm/asm/-/tags/ASM_9_0
* https://repo1.maven.org/maven2/org/ow2/asm/asm/9.0/
* https://asm.ow2.io/versions.html

### CODE REVIEW

**Comment by mkurz** [comment]
@googlebot I signed it!

**Comment by GedMarc** [comment]
you can also use https://search.maven.org/artifact/com.guicedee.services/guice for builds that are actually built in the JDK and modular compliant (contains module-info.java for the entire dependency tree)

GuicedEE also provides JRE15 libraries built with module definitions for most popular frameworks in order to build JLink native runtimes to take advantages of the JRT and strict modular performance and coding updates

**Comment by GedMarc** [comment]
1.19.0 is releasing with ASM 9.0 and Hazelcast 4.0.3 for JDK 16 support

**Comment by mkurz** [comment]
@GedMarc so your library is a drop-in replacement for the original guice jar?

**Comment by GedMarc** [comment]
Yes, recompiled in the associated JDK and with a module  -info,
All the operational extensions are available as well, spring and dagger have been excluded for obvious reasons, being the likelihood of them supporting modular is 0.

The entire chain is modular, so That includes all dependencies, javax.inject, guava etc

Maybe the only thing to note is guice-servlet is servlet 4.0.1 but servlet is always backwards compatible

**Comment by GedMarc** [comment]
Hmm site is out of date lol, all valid still. www.guicedee.com

**Pull request closed without merging**
