### PR TITLE
Update asm version to 9.4.

### LINKED ISSUE #1654: Support for running in Java 19 by upgrading ASM
The bundled ASM 9.2 doesn't support reading Java 19 class file version 63. While class generation works fine, the error reporting functionality throws the following error

```
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException: Unsupported class file major version 63
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2055)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3966)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3989)
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4950)
        at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4956)
        at com.google.inject.internal.util.StackTraceElements.forMember(StackTraceElements.java:67)
        at com.google.inject.internal.SourceFormatter.formatMember(SourceFormatter.java:91)
        at com.google.inject.internal.SourceFormatter.format(SourceFormatter.java:53)
        at com.google.inject.internal.GenericErrorDetail.formatDetail(GenericErrorDetail.java:26)
        at com.google.inject.spi.ErrorDetail.format(ErrorDetail.java:63)
        at com.google.inject.internal.Messages.formatMessages(Messages.java:90)
        at com.google.inject.CreationException.getMessage(CreationException.java:50)
....
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 63
        at com.google.inject.internal.asm.$ClassReader.<init>(ClassReader.java:199)
        at com.google.inject.internal.asm.$ClassReader.<init>(ClassReader.java:180)
        at com.google.inject.internal.asm.$ClassReader.<init>(ClassReader.java:166)
        at com.google.inject.internal.asm.$ClassReader.<init>(ClassReader.java:287)
        at com.google.inject.internal.util.LineNumbers.<init>(LineNumbers.java:69)
        at com.google.inject.internal.util.StackTraceElements$1.load(StackTraceElements.java:48)
        at com.google.inject.internal.util.StackTraceElements$1.load(StackTraceElements.java:44)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3533)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2282)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2159)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2049)
        ... 44 more
```

### PR DESCRIPTION
**Pull request by jaroslawr**
Fixes #1654.

### CODE REVIEW

**Comment by jaroslawr** [comment]
(I added the CLA)

**Comment by ninja-** [comment]
In the meantime, I would recommend excluding transitive asm dependency in your build.gradle and shading your own version of asm, for anyone needing Java 19

**Comment by nikammerlaan** [comment]
@ninja- Can you elaborate on how you excluded ASM? Guice relocates ASM into it's own source, so it's not as simple as a regular transitive dependency override.

**Comment by mcculls** [comment]
The jar before ASM is shaded is kept as part of the build process, for
5.1.0 it can be found at:

https://repo1.maven.org/maven2/com/google/inject/guice/5.1.0/guice-5.1.0-classes.jar

or using Maven:

    <dependency>
      <groupId>com.google.inject</groupId>
      <artifactId>guice</artifactId>
      <classifier>classes</classifier>
      <version>5.1.0</version>
    </dependency>

you can then add your own version of ASM on the classpath and it should
pick it up.

**Comment by ninja-** [comment]
@nikammerlaan right, if it's relocated I probably missed that. in such case the reason why my app is still working on newest Java, is that I left the compiler versions at earlier Java:

```
configure<JavaPluginExtension> {
    sourceCompatibility = JavaVersion.VERSION_15
    targetCompatibility = JavaVersion.VERSION_15
}
```

it doesn't seem to have any negative consequences, especially that I am using Kotlin

**Pull request closed without merging**
